name: Build and Release (Raspberry Pi)

on:
  push:
    tags:
      - 'v*' # Triggers when you push a tag like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # adjust as needed

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish for Raspberry Pi (ARM)
        run: dotnet publish -c Release -r linux-arm64 --self-contained true -o ./publish

      - name: Archive published files
        run: |
          cd publish
          zip -r ../app-linux-arm64.zip .
          cd ..

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-linux-arm64
          path: app-linux-arm64.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-linux-arm64
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app-linux-arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
